version: '3.8'

services:

  mlops:
    build:
      context: .
      dockerfile: Docker/mlops.Dockerfile
    volumes:
      - ..:/workspaces:cached
    command: sleep infinity
    # environment:
    #   - WORKSPACEFOLDER=/workspace/qubika-mlops-challenge
    env_file: Docker/parameters.env
  # app:
  #   depends_on:
  #     - mlflow
  #   build:
  #     context: .
  #     dockerfile: Docker/app.Dockerfile
  #   network_mode: service:db
  #   # command: sleep infinity
  #   environment:
  #     - WORKSPACEFOLDER=/workspace/
  #   env_file: Docker/parameters.env
  #   restart: unless-stopped

  # mlflow:
  #   depends_on:
  #     - db
  #   build:
  #     context: .
  #     dockerfile: Docker/mlflow.Dockerfile
  #   network_mode: service:db
  #   env_file: Docker/parameters.env
  #   restart: unless-stopped

  # db:
  #   image: postgres:latest
  #   restart: unless-stopped
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_DB: postgres
  #     POSTGRES_PASSWORD: postgres

volumes:
  postgres-data:
